# go mod Mapping pseudo-versions to commits
alias glvmc="TZ=UTC git log --pretty='%Cred%ad-%h%Creset -%C(auto)%d%Creset %s %C(bold blue)<%an>%Creset' --date=format-local:%Y%m%d%H%M%S --abbrev=12 | head -n1"
