kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: tslime
networking:
  # the default CNI will not be installed, default is the kindnetd
  disableDefaultCNI: true
  ## ipv4/ipv6/dual
  # ipFamily: dual
  ## iptables or ipvs
  #kubeProxyMode: iptables
  ## configure the subnet used for pod IPs, default is [10.244.0.0/16,fd00:10:244::/56]
  podSubnet: 10.201.0.0/16
  ## configure the subnet used for service IPs, default is [10.96.0.0/16,fd00:10:96::/56]
  serviceSubnet: 10.202.0.0/16
nodes:
- role: control-plane
  extraMounts:
  # add the docker config file to the node
  - hostPath: /home/wangkang08/.docker/config.json
    containerPath: /var/lib/kubelet/config.json
    readOnly: true
    propagation: HostToContainer
  # image: xxx
- role: worker
  extraMounts:
  # add the docker config.json to the node
  - hostPath: /home/wangkang08/.docker/config.json
    containerPath: /var/lib/kubelet/config.json
    readOnly: true
    propagation: HostToContainer
  # image: xxx
# - role: worker
#   extraMounts:
#   # add the docker config.json to the node
#   - hostPath: /home/wangkang08/.docker/config.json
#     containerPath: /var/lib/kubelet/config.json
#     readOnly: true
#     propagation: HostToContainer
#   # image: xxx